version: '3'
services:
  web:
    #    image: maven:3.8.5-jdk-11
    build: .
    #    command: mvn spring-boot:run
    container_name: web-server
    restart: always
    ports:
      - "8088:8088"
    depends_on:
      - mysql-db
      #      - zookeeper
      - kafka
    #    volumes:
    #      - /:/app
    #      - ~/.m2:/root/.m2
    #    working_dir: ~/
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/boost-crawel?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      BOOTSTRAP_SERVERS_CONFIG: kafka:9092
      web.craweler.kafka.bootstrapAddress: kafka:9092
      bootstrap.servers: kafka:9092
    networks:
      - cp

  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    restart: always
    networks:
      - cp

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - cp

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - cp

volumes:
  dbdata:
  imagedata:

networks:
  cp:
    name: cp_network
